// Generated by CoffeeScript 2.3.0
var NameResolver;

NameResolver = function(bundle, packages) {
  var packIds;
  if (!bundle.dev) {
    return function(asset) {
      return String(asset.id);
    };
  }
  packIds = [];
  packages.forEach(function(pack, i) {
    var dupe, name, version;
    ({name, version} = pack.data);
    dupe = packIds[name];
    if (dupe !== void 0) {
      if (dupe !== true) {
        packIds[name] = true;
        packIds[dupe] = name + '@' + packIds[dupe].data.version;
      }
      packIds[i] = name + '@' + version;
    } else {
      packIds[name] = i;
      packIds[i] = name;
    }
  });
  return function(asset) {
    return `'${packIds[packages.indexOf(asset.owner)]}/${asset.name}'`;
  };
};

module.exports = NameResolver;
